// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz5zXSY7cTgscD4ZrYzKzWgs49_Xn6eXQ',
    appId: '1:42016626917:web:aa0cda51f94017a5d99c0c',
    messagingSenderId: '42016626917',
    projectId: 'phraraonic',
    authDomain: 'phraraonic.firebaseapp.com',
    databaseURL: 'https://phraraonic-default-rtdb.firebaseio.com',
    storageBucket: 'phraraonic.appspot.com',
    measurementId: 'G-VMM2066P1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEm6mLb3u8OQkQB_jGZz5Y32qvFFVLIFk',
    appId: '1:42016626917:android:f3b49575e7135290d99c0c',
    messagingSenderId: '42016626917',
    projectId: 'phraraonic',
    databaseURL: 'https://phraraonic-default-rtdb.firebaseio.com',
    storageBucket: 'phraraonic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwJsWr-zzFfpvvsDoHaucuj9CZfOJfKg',
    appId: '1:42016626917:ios:d6cee2dfb47cf8b7d99c0c',
    messagingSenderId: '42016626917',
    projectId: 'phraraonic',
    databaseURL: 'https://phraraonic-default-rtdb.firebaseio.com',
    storageBucket: 'phraraonic.appspot.com',
    iosBundleId: 'com.example.pharonic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwJsWr-zzFfpvvsDoHaucuj9CZfOJfKg',
    appId: '1:42016626917:ios:d6cee2dfb47cf8b7d99c0c',
    messagingSenderId: '42016626917',
    projectId: 'phraraonic',
    databaseURL: 'https://phraraonic-default-rtdb.firebaseio.com',
    storageBucket: 'phraraonic.appspot.com',
    iosBundleId: 'com.example.pharonic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz5zXSY7cTgscD4ZrYzKzWgs49_Xn6eXQ',
    appId: '1:42016626917:web:7b58279b06cb4b44d99c0c',
    messagingSenderId: '42016626917',
    projectId: 'phraraonic',
    authDomain: 'phraraonic.firebaseapp.com',
    databaseURL: 'https://phraraonic-default-rtdb.firebaseio.com',
    storageBucket: 'phraraonic.appspot.com',
    measurementId: 'G-HW9CXL6VP3',
  );

}